############################
## CHANGE THESE
############################

baseURL: 'https://Rahim7X.github.io/Rahim7X-app'
title: Rahim7X-app

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


